config/routes.rb
Expertiza::Application.routes.draw do |map|

  resources :admin do
    collection do
      get :list_super_administrators
      get :list_administrators
      get :list_instructors
      get :new_administrator
      get :new_instructor
      post :create_instructor
      get :remove_instructor
      post :remove_instructor
      get :show_instructor
    end
  end

  resources :advertise_for_partner do
    collection do
      get :edit
      get :remove
      post ':id', action: :update
    end
  end

  resources :assessment360 do
    collection do
      get :one_course_all_assignments
    end
  end

  resources :assignments do
    collection do
      get :associate_assignment_with_course
      get :copy
      get :toggle_access
      post :remove_assignment_from_course
      get :set_questionnaire
      get :set_due_date
      get :delete_all_questionnaires
      get :delete_all_due_dates
    end
  end

  resources :auth do
    collection do
      post :login
      post :logout
    end
  end

  resources :author_feedback_questionnaires, controller: 'questionnaires'

  resources :content_pages do
    collection do
      get :list
      get ':page_name', action: :view
    end
  end

  resources :controller_actions do
    collection do
      get 'list'
      post ':id', action: :update
      get 'new_for'
    end
  end

  resources :course do
    collection do
      post :delete
      post :toggle_access
      get :copy
      get :view_teaching_assistants
      post :add_ta
      get :auto_complete_for_user_name
      post :remove_ta
    end
  end

  resources :course_evaluation do
    collection do
      get :list
    end
  end

  resources :eula do
    collection do
      get :accept
      get :decline
      get :display
    end
  end

  resources :export_file do
    collection do
      get :start
    end
  end

  resources :grades do
    collection do
      get :view
      get :view_my_scores
      get :instructor_review
      get :remove_hyperlink
      get :conflict_notification
    end
  end

  resources :impersonate do
    collection do
      get :start
      post :impersonate
    end
  end

  resources :import_file do
    collection do
      get :start
      get :import
    end
  end

  resources :institutions

  resources :invitation

  resources :join_team_requests

  resources :leaderboard, constraints: { id: /\d+/ } do
    collection do
      get :index
    end
  end
  match 'leaderboard/index', controller: :leaderboard, action: :index

  resources :markup_styles

  resources :menu_items do
    collection do
      get :move_down
      get :move_up
      get :new_for
      get :link
      get :list
    end
  end

  resources :participants do
    collection do
      get :add
      post :add
      get :auto_complete_for_user_name
      get :list
      get :change_handle
      post :delete
      get :inherit
      get :bequeath_all
    end
  end

  resources :password_retrieval do
    collection do
      get :forgotten
      post :send_password
    end
  end

  resources :permissions, constraints: { id: /\d+/ } do
    collection do
      get :list
      get ':id', action: :show
      post ':id', action: :update
      delete ':id', action: :destroy
    end
  end

  resources :profile do
    collection do
      get :edit
    end
  end

  resources :publishing do
    collection do
      get :view
      post :update_publish_permissions
      post :set_publish_permission
      get :grant
      get :grant_with_private_key
      post :grant_with_private_key
      get :set_publish_permission
    end
  end

  resources :questionnaires do
    collection do
      post :toggle_access
      get :copy
      post :select_questionnaire_type
    end
  end
  resources :review_questionnaires, controller: :questionnaires
  resources :metareview_questionnaires, controller: :questionnaires
  resources :teammate_review_questionnaires, controller: :questionnaires
  resources :survey_questionnaires, controller: :questionnaires
  resources :global_survey_questionnaires, controller: :questionnaires
  resources :course_evaluation_questionnaires, controller: :questionnaires

  resources :response do
    collection do
      get :new_feedback
      get :view
      post :delete
    end
  end

  resources :review_mapping do
    collection do
      get :list_mappings
      get :review_report
    end
  end

  resources :review_files do
    collection do
      get :show_all_submitted_files
    end
  end

  resources :roles do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :roles_permissions do
    collection do
      get :new_permission_for_role
    end
  end

  resources :sign_up_sheet do
    collection do
      get :add_signup_topics
      get :signup_topics
      get :view_publishing_rights
      get :save_topic_dependencies
      get :delete
      get :edit
      get :save_topic_deadlines
      get :signup
      get :delete_signup
    end
  end

  resources :site_controllers do
    collection do
      get 'list'
      get 'new_called'
    end
  end

  resources :statistics do
    collection do
      get :list_surveys
      get :list
      get :view_responses
    end
  end

  resources :student_review do
    collection do
      get :list
    end
  end

  resources :student_task do
    collection do
      get :list
      get :view
    end
  end

  resources :student_team do
    collection do
      get :view
      get :edit
      get :leave
      get :auto_complete_for_user_name
    end
  end

  resources :submitted_content do
    collection do
      get :view
      get :edit
    end
  end

  resources :suggestion do
    collection do
      get :list
    end
  end

  resources :survey do
    collection do
      get :assign
    end
  end

  resources :survey_deployment do
    collection do
      get :list
      get :delete
      get :reminder_thread
    end
  end

  resources :survey_response do
    collection do
      get :view_responses
    end
  end

  resources :system_settings do
    collection do
      get :list
    end
  end

  resources :teams do
    collection do
      get :list
    end
  end

  resources :tree_display do
    collection do
      get ':action'
      post 'list'
    end
  end

  resources :users, constraints: { id: /\d+/ } do
    collection do
      get :list
      post ':id', action: :update
      get :show_selection
      get :auto_complete_for_user_name
      get :keys
    end
  end

  match '/menu/*name', controller: :menu_items, action: :link
  match ':page_name', controller: :content_pages, action: :view, method: :get

  root to: 'content_pages#view', page_name: 'home'

  map.connect 'question/select_questionnaire_type', :controller => "questionnaire", :action => 'select_questionnaire_type'
  map.connect ':controller/service.wsdl', :action => 'wsdl'
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |config|
    config.validates_uniqueness_of_email_field_options = {:if => lambda { false }} # Don't validate email uniqueness
    config.crypto_provider = Authlogic::CryptoProviders::Sha1
    Authlogic::CryptoProviders::Sha1.join_token = ''
    Authlogic::CryptoProviders::Sha1.stretches = 1
  end

  has_many :participants, :class_name => 'Participant', :foreign_key => 'user_id', :dependent => :destroy
  has_many :assignment_participants, :class_name => 'AssignmentParticipant', :foreign_key => 'user_id', :dependent => :destroy
  has_many :assignments, :through => :participants

  has_many :teams_users, :dependent => :destroy
  has_many :teams, :through => :teams_users

  has_many :children, class_name: 'User', :foreign_key => 'parent_id'
  belongs_to :parent, class_name: 'User'
  belongs_to :role

  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :email, :message => "can't be blank"
  validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i, :allow_blank => true

  before_validation :randomize_password, :if => lambda { |user| user.new_record? && user.password.blank? } # AuthLogic
  after_create :email_welcome

  scope :superadministrators, -> { where role_id: Role.superadministrator }
  scope :superadmins, -> { superadministrators }
  scope :administrators, -> { where role_id: Role.administrator }
  scope :admins, -> { administrators }
  scope :instructors, -> { where role_id: Role.instructor }
  scope :tas, -> { where role_id: Role.ta }
  scope :students, -> { where role_id: Role.student }

  def salt_first?
    true
  end

  def get_available_users(name)
    lesser_roles = role.get_parents
    all_users = User.find(:all, :conditions => ['name LIKE ?', "#{name}%"], :limit => 20) # higher limit, since we're filtering
    visible_users = all_users.select{|user| lesser_roles.include? user.role}
    return visible_users[0,10] # the first 10
  end

  def can_impersonate?(user)
    user &&
      self == user || # can impersonate self
      self.is_teaching_assistant_for?(user) || #TAs can impersonate their students
      self.is_creator_of?(user) ||
      can_impersonate?(user.parent) # recursive
  end

  def first_name
    fullname[/,.+/][/\w+/] if fullname
  end

  def super_admin?
    role.name == 'Super-Administrator'
  end

  def admin?
    role.name == 'Administrator' || super_admin?
  end

  def is_creator_of?(user)
    self == user.creator
  end

  def assign_random_password
    if self.password.blank?
      self.password = self.random_password
    end
  end

  # Function which has a MailerHelper which sends the mail welcome email to the user after signing up
  def email_welcome
    MailerHelper::send_mail_to_user(self, "Your Expertiza password has been created", "user_welcome", password)
  end

  def check_password(password)
    Authlogic::CryptoProviders::Sha1.stretches = 1
    Authlogic::CryptoProviders::Sha1.matches?(password, *[self.password_salt.to_s + password])
  end

  # Resets the password to be mailed to the user
  def reset_password
    randomize_password
    save
    password
  end

  def self.random_password(size=8)
    random_pronouncable_password((size/2).round) + rand.to_s[2,3]
  end

  def self.import(row,session,id = nil)
    if row.length != 4
      raise ArgumentError, "Not enough items" 
    end    
    user = User.find_by_name(row[0])    

    if user == nil
      attributes = ImportFileHelper::define_attributes(row)
      user = ImportFileHelper::create_new_user(attributes,session)
    else
      user.password = row[3].strip
      user.email = row[2].strip
      user.fullname = row[1].strip
      user.parent_id = (session[:user]).id
      user.save
    end
  end  

  def get_author_name
    return self.fullname
  end

  def self.yesorno(elt)
    if elt==true
      "yes"
    elsif elt ==false
      "no"
    else
      ""
    end
  end    

  # locate User based on provided login.
  # If user supplies e-mail or name, the
  # helper will try to find that User account.
  def self.find_by_login(login)
    user = User.find_by_email(login)
    if user == nil
      items = login.split("@")
      shortName = items[0]
      userList = User.find(:all, {:conditions=> ["name =?",shortName]})
      if userList != nil && userList.length == 1
        user = userList.first            
      end
    end
    return user     
  end 

  def set_instructor (new_assign)  
    new_assign.instructor_id = self.id  
  end

  def get_instructor
    self.id
  end

  def instructor_id
    case role.name
    when 'Instructor' then id
    when 'Teaching Assistant' then Ta.get_my_instructor(id)
    else raise NotImplementedError.new "for role #{role.name}"
    end
  end

  def set_courses_to_assignment 
    @courses = Course.find_all_by_instructor_id(self.id, :order => 'name')    
  end

  # generate a new RSA public/private key pair and create our own X509 digital certificate which we 
  # save in the database. The private key is returned by the method but not saved.
  def generate_keys
    # check if we are replacing a digital certificate already generated
    replacing_key = true if (!self.digital_certificate.nil?)

    # generate the new key pair
    new_key = OpenSSL::PKey::RSA.generate( 1024 )
    self.public_key = new_key.public_key.to_pem

    save

    # when replacing an existing key, update any digital signatures made previously with the new key
    if (replacing_key)
      participants = AssignmentParticipant.find_all_by_user_id(self.id)
      for participant in participants
        if (participant.permission_granted)
          AssignmentParticipant.grant_publishing_rights(new_key.to_pem, [ participant ]) 
        end
      end
    end

    # return the new private key
    new_key.to_pem
  end

  def initialize(attributes = nil)
    super(attributes)
    Authlogic::CryptoProviders::Sha1.stretches = 1
    @email_on_review = true
    @email_on_submission = true
    @email_on_review_of_review = true
  end

  def self.export(csv, parent_id, options)
    users = User.find(:all)
    users.each {|user|
      tcsv = Array.new
      if (options["personal_details"] == "true")
        tcsv.push(user.name, user.fullname, user.email)
      end
      if (options["role"] == "true")
        tcsv.push(user.role.name)
      end
      if (options["parent"] == "true")
        tcsv.push(user.parent.name)
      end
      if (options["email_options"] == "true")
        tcsv.push(user.email_on_submission, user.email_on_review, user.email_on_review_of_review)
      end
      if (options["handle"] == "true")
        tcsv.push(user.handle)
      end
      csv << tcsv
    }
  end

  def creator
    parent
  end

  def self.get_export_fields(options)
    fields = Array.new
    if (options["personal_details"] == "true")
      fields.push("name", "full name", "email")
    end
    if (options["role"] == "true")
      fields.push("role")
    end
    if (options["parent"] == "true")
      fields.push("parent")
    end
    if (options["email_options"] == "true")
      fields.push("email on submission", "email on review", "email on metareview")
    end
    if (options["handle"] == "true")
      fields.push("handle")
    end
    return fields
  end

  def self.from_params(params)
    if params[:user_id]
      user = User.find(params[:user_id])
    else
      user = User.find_by_name(params[:user][:name])
    end
    if user.nil?
      newuser = url_for :controller => 'users', :action => 'new'
      raise "Please <a href='#{newuser}'>create an account</a> for this user to continue."
    end
    return user
  end

  def is_teaching_assistant_for?(student)
    return false if self.role.name != 'Teaching Assistant'
    return false if student.role.name != 'Student'
    return true if Course.all.any? do |c|
      c.participants.all(:conditions => "user_id=#{student.id}").size > 0 &&
      c.participants.all(:conditions => "user_id=#{id}").size > 0
    end
    return false
  end

  def is_teaching_assistant?
    false
  end

end

app/views/mine_review_data/view_review_charts.html.erb
<h1>Mine Review Data</h1>

<div>
  <table align="left">
    <tr>
      <td style="width: 40px;">
        <%= form_tag({:course_list=>@course_list}) do %>
            Select Graph :
            <br/>
            <select name='display[graph_type]' style="width: 15em">
              <% @review_graphs.each do |graph| %>
                  <% if @selected_graph==graph %>
                      <option value='<%= graph %>' selected="selected"><%= graph %></option>
                  <% else %>
                      <option value='<%= graph %>' ><%= graph %></option>
                  <% end %>
              <% end %>
            </select>
            <br/>
            <br/>
            Select Course:
            <br/>
            <select name='display[course]' style="width: 15em">
              <% @courses.sort_by {|x| x.name}.each do |course| %>
                  <% if @selected_course.to_s==course.id.to_s %>
                      <option value='<%= course.id%>' selected="selected"><%= course.name %></option>
                  <% else %>
                      <option value='<%= course.id%>' ><%= course.name %></option>
                  <% end %>
              <% end %>
            </select>
            <br/>
            <%= submit_tag "Add course" %>
        <% end %>
      </td>
      <td>
        <div>
          <% if @assignments and !@assignments.empty? %>
              <table>
                <%= form_tag({:course_list=>@course_list, :course_id=>@selected_course, :graph_type=>@selected_graph}) do %>
                    <% index=0 %>
                    <% @assignments.each do |course, assignments| %>
                        <% if course and !course.empty? %>
                            <tr>
                              <td style="width:10em"><%= @controller.get_course_name(course) %></td>
                              <td><a id="<%= index %>Link" name="<%= index %>Link" href="#" <% if assignments.length > 0  %>onclick="toggleList('<%= index %>',<%= assignments.length ==0? 0:1 %>);alternate('theTable');return false;"><img src="/images/expand.png"><% else %>onclick="return false;"><img src="/images/noaction.png"><% end %></a></td>

                              <td id="<%= index %>_1" name="<%= index %>_1"  style="display: none;">
                                <table><tr>
                                  <% assignments.each_with_index do |assignment, index| %>
                                      <% if index%4 ==0 %>
                                          </tr><tr><td>
                                      <%else %>
                                          <td>
                                      <%end %>
                                      <% if @selected_assignments.include?(assignment) %>
                                          <%= check_box_tag 'assignment_ids[]', assignment.id, true%>
                                          <%= assignment.name %>

                                      <% else %>
                                          <%= check_box_tag 'assignment_ids[]', assignment.id, false%>
                                          <%= assignment.name %>

                                      <% end %>

                                      </td>
                                  <% end %>
                                  </tr></table>
                              </td>
                            </tr>
                        <% end %>
                        <% index=index+1 %>
                    <%end %>
                    <tr><td><%= submit_tag "Update Graph" %></td></tr>
                <% end %>
              </table>
          <% end %>
        </div>

      </td>
    </tr>
    <tr>
      <td>

        <% if @dataset_names %>
            <div class ="taskbox" float="left">
              Y-axis Legend:<br/>
              <% @dataset_names.each do |ds| %>
                  <span style="background-color:<%=ds[1]%>;color=<%=ds[1]%>;"> . </span> <%=ds[0]%><br/>
              <% end %>
            </div>
        <% end %>
        <% if @xaxis_legend %>
            <div class ="taskbox" float="left">
              X-axis Legend (Review Strategy):<br/>
              <% @xaxis_legend.each_with_index do |x, index| %>
                  <span class="tasknum" style="background-color:black"> <%= index+1 %> </span>
                  <%= x %>
                  <br/>
              <% end %>
            </div>
        <% elsif @selected_assignments %>
            <div class ="taskbox" float="left">
              X-axis Legend (Assignments):<br/>
              <% @selected_assignments.each_with_index do |assignment, index| %>
                  <span class="tasknum" style="background-color:black"> <%= index+1 %> </span>
                  <%= @controller.get_course_name(assignment.course_id) %>:<%=assignment.name %>
                  <br/>
              <% end %>
            </div>
        <% end %>
      </td>
      <td>
        <br/>
        <div align="left">
          <% if @chart1 %>
              <div align="left"><%= @selected_graph %></div>
              <img src= "<%= @chart1.to_url %>"/>
          <% end %>

        </div>

      </td>
    </tr>
    <tr><td colspan="2">
      <% if @table %>
          <div> Table:<br/>
            <%= @table %>
          </div><% end %>
    </td></tr>
  </table>

</div>