config/routes.rb
Expertiza::Application.routes.draw do |map|

  resources :admin do
    collection do
      get :list_super_administrators
      get :list_administrators
      get :list_instructors
      get :new_administrator
      get :new_instructor
      post :create_instructor
      get :remove_instructor
      post :remove_instructor
      get :show_instructor
    end
  end

  resources :advertise_for_partner do
    collection do
      get :edit
      get :remove
      post ':id', action: :update
    end
  end

  resources :assessment360 do
    collection do
      get :one_course_all_assignments
    end
  end

  resources :assignments do
    collection do
      get :associate_assignment_with_course
      get :copy
      get :toggle_access
      post :remove_assignment_from_course
      get :set_questionnaire
      get :set_due_date
      get :delete_all_questionnaires
      get :delete_all_due_dates
    end
  end

  resources :auth do
    collection do
      post :login
      post :logout
    end
  end

  resources :author_feedback_questionnaires, controller: 'questionnaires'

  resources :content_pages do
    collection do
      get :list
      get ':page_name', action: :view
    end
  end

  resources :controller_actions do
    collection do
      get 'list'
      post ':id', action: :update
      get 'new_for'
    end
  end

  resources :course do
    collection do
      post :delete
      post :toggle_access
      get :copy
      get :view_teaching_assistants
      post :add_ta
      get :auto_complete_for_user_name
      post :remove_ta
    end
  end

  resources :course_evaluation do
    collection do
      get :list
    end
  end

  resources :eula do
    collection do
      get :accept
      get :decline
      get :display
    end
  end

  resources :export_file do
    collection do
      get :start
    end
  end

  resources :grades do
    collection do
      get :view
      get :view_my_scores
      get :instructor_review
      get :remove_hyperlink
      get :conflict_notification
    end
  end

  resources :impersonate do
    collection do
      get :start
      post :impersonate
    end
  end

  resources :import_file do
    collection do
      get :start
      get :import
    end
  end

  resources :institutions

  resources :invitation

  resources :join_team_requests

  resources :leaderboard, constraints: { id: /\d+/ } do
    collection do
      get :index
    end
  end
  match 'leaderboard/index', controller: :leaderboard, action: :index

  resources :markup_styles

  resources :menu_items do
    collection do
      get :move_down
      get :move_up
      get :new_for
      get :link
      get :list
    end
  end

  resources :participants do
    collection do
      get :add
      post :add
      get :auto_complete_for_user_name
      get :list
      get :change_handle
      post :delete
      get :inherit
      get :bequeath_all
    end
  end

  resources :password_retrieval do
    collection do
      get :forgotten
      post :send_password
    end
  end

  resources :permissions, constraints: { id: /\d+/ } do
    collection do
      get :list
      get ':id', action: :show
      post ':id', action: :update
      delete ':id', action: :destroy
    end
  end

  resources :profile do
    collection do
      get :edit
    end
  end

  resources :publishing do
    collection do
      get :view
      post :update_publish_permissions
      post :set_publish_permission
      get :grant
      get :grant_with_private_key
      post :grant_with_private_key
      get :set_publish_permission
    end
  end

  resources :questionnaires do
    collection do
      post :toggle_access
      get :copy
      post :select_questionnaire_type
    end
  end
  resources :review_questionnaires, controller: :questionnaires
  resources :metareview_questionnaires, controller: :questionnaires
  resources :teammate_review_questionnaires, controller: :questionnaires
  resources :survey_questionnaires, controller: :questionnaires
  resources :global_survey_questionnaires, controller: :questionnaires
  resources :course_evaluation_questionnaires, controller: :questionnaires

  resources :response do
    collection do
      get :new_feedback
      get :view
      post :delete
    end
  end

  resources :review_mapping do
    collection do
      get :list_mappings
      get :review_report
    end
  end

  resources :review_files do
    collection do
      get :show_all_submitted_files
    end
  end

  resources :roles do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :roles_permissions do
    collection do
      get :new_permission_for_role
    end
  end

  resources :sign_up_sheet do
    collection do
      get :add_signup_topics
      get :signup_topics
      get :view_publishing_rights
      get :save_topic_dependencies
      get :delete
      get :edit
      get :save_topic_deadlines
      get :signup
      get :delete_signup
    end
  end

  resources :site_controllers do
    collection do
      get 'list'
      get 'new_called'
    end
  end

  resources :statistics do
    collection do
      get :list_surveys
      get :list
      get :view_responses
    end
  end

  resources :student_review do
    collection do
      get :list
    end
  end

  resources :student_task do
    collection do
      get :list
      get :view
    end
  end

  resources :student_team do
    collection do
      get :view
      get :edit
      get :leave
      get :auto_complete_for_user_name
    end
  end

  resources :submitted_content do
    collection do
      get :view
      get :edit
    end
  end

  resources :suggestion do
    collection do
      get :list
    end
  end

  resources :survey do
    collection do
      get :assign
    end
  end

  resources :survey_deployment do
    collection do
      get :list
      get :delete
      get :reminder_thread
    end
  end

  resources :survey_response do
    collection do
      get :view_responses
    end
  end

  resources :system_settings do
    collection do
      get :list
    end
  end

  resources :teams do
    collection do
      get :list
    end
  end

  resources :tree_display do
    collection do
      get ':action'
      post 'list'
    end
  end

  resources :users, constraints: { id: /\d+/ } do
    collection do
      get :list
      post ':id', action: :update
      get :show_selection
      get :auto_complete_for_user_name
      get :keys
    end
  end

  match '/menu/*name', controller: :menu_items, action: :link
  match ':page_name', controller: :content_pages, action: :view, method: :get

  root to: 'content_pages#view', page_name: 'home'

  map.connect 'question/select_questionnaire_type', :controller => "questionnaire", :action => 'select_questionnaire_type'
  map.connect ':controller/service.wsdl', :action => 'wsdl'
end

app/models/join_team_request.rb
class JoinTeamRequest < ActiveRecord::Base
 belongs_to :team
 has_one :participant
end

app/controllers/join_team_requests_controller.rb
class JoinTeamRequestsController < ApplicationController
  # GET /join_team_requests
  # GET /join_team_requests.xml
  def index
    @join_team_requests = JoinTeamRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @join_team_requests }
    end
  end

  # GET /join_team_requests/1
  # GET /join_team_requests/1.xml
  def show
    @join_team_request = JoinTeamRequest.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @join_team_request }
    end
  end

  # GET /join_team_requests/new
  # GET /join_team_requests/new.xml
  def new
    @join_team_request = JoinTeamRequest.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @join_team_request }
    end
  end

  # GET /join_team_requests/1/edit
  def edit
    @join_team_request = JoinTeamRequest.find(params[:id])
  end

  # POST /join_team_requests
  # POST /join_team_requests.xml
  #create a new join team request entry for join_team_request table and add it to the table
  def create
    @join_team_request = JoinTeamRequest.new
    @join_team_request.comments = params[:comments]
    @join_team_request.status = 'P'
    @join_team_request.team_id = params[:team_id]

    participant = Participant.find_by_user_id_and_parent_id(session[:user][:id],params[:assignment_id])
    @join_team_request.participant_id= participant.id
    respond_to do |format|
      if @join_team_request.save
        format.html { redirect_to(@join_team_request, :notice => 'JoinTeamRequest was successfully created.') }
        format.xml  { render :xml => @join_team_request, :status => :created, :location => @join_team_request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @join_team_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /join_team_requests/1
  # PUT /join_team_requests/1.xml
  #update join team request entry for join_team_request table and add it to the table
  def update
    @join_team_request = JoinTeamRequest.find(params[:id])
    respond_to do |format|
      if @join_team_request.update_attributes(params[:join_team_request])
        format.html { redirect_to(@join_team_request, :notice => 'JoinTeamRequest was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @join_team_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /join_team_requests/1
  # DELETE /join_team_requests/1.xml

  def destroy
    @join_team_request = JoinTeamRequest.find(params[:id])
    @join_team_request.destroy

    respond_to do |format|
      format.html { redirect_to(join_team_requests_url) }
      format.xml  { head :ok }
    end
  end
  #decline request to join the team...
  def decline
    @join_team_request = JoinTeamRequest.find(params[:id])
    @join_team_request.status = 'D'
    @join_team_request.save
    redirect_to :controller => 'student_team', :action => 'view', :id=>params[:teams_user_id]
  end
end

app/helpers/join_team_requests_helper.rb
module JoinTeamRequestsHelper
end

app/views/join_team_requests/_list_received.html.erb
<% @join_team_requests = JoinTeamRequest.find_all_by_team_id(team_id) %>
<h2>Received Requests</h2>
<table>
  <tr>
    <th>
      Name
    </th>
    <th>
      Comments
    </th>
    <th>Action</th>
    <th>
      Sent at
    </th>
  </tr>

  <% if @join_team_requests != nil %>

    <% @join_team_requests.each do |join_team_request| %>
      <% if join_team_request.status=='P' %>
        <tr>

          <td>
            <%= User.find(Participant.find(join_team_request.participant_id).user_id).name %>
          </td>
          <td>
            <%= join_team_request.comments %>
          </td>
          <td>
            <table>
              <tr>
                <td>
                  <%= form_tag :controller => 'invitation', :action => 'create' do %>
                    <%= hidden_field_tag 'team_id', team_id %>
                    <%= hidden_field_tag 'student_id', teams_user_id %>
                    <%= hidden_field_tag 'session[:dummy][:assignment_id]', Participant.find(join_team_request.participant_id).parent_id %>
                    <%= hidden_field_tag 'user[name]', User.find(Participant.find(join_team_request.participant_id).user_id).name %>
                    <input type='submit' value='Invite'/>
                  <% end %>
                </td>
                <td>
                  <%= button_to 'Decline', :controller => 'join_team_requests', :action => 'decline', :id=>join_team_request.id, :teams_user_id=>teams_user_id %>
                </td>
              </tr>
            </table>

          </td>
          <td>
            <%= join_team_request.created_at %>
          </td>
        </tr>
      <% end %>

    <% end %>
  <% else %>
    You Dont have any requests

  <% end %>
</table>

app/views/join_team_requests/_list_sent.html.erb
<h2>Sent Requests </h2>

  <table cellpadding="5">
    <tr>
      <th>
        Team
      </th>
      <th>
        Comments
      </th>
      <th>Status</th>
      <th>Sent at</th>
    </tr>
    <% participant = Participant.find_by_user_id_and_parent_id(session[:user].id, assignment_id)
       requests=JoinTeamRequest.find_all_by_participant_id(participant.id) %>
    <% if requests != nil %>

        <% requests.each do |request| %>

            <tr>
              <td>
                <% if Team.exists?(request.team_id)==false  %>
                  <font color="#FF0000">  This team no longer exists. </font>
                <% else %>
                <%= Team.find(request.team_id).name %>
                <% end %>
              </td>
              <td>
                <%= request.comments %>
              </td>
              <td>
                <% if request.status == 'P' %>
                    <%= "Pending" %>
                <% elsif request.status == 'A' %>
                     <%= "Accepted" %>
                <% else %>
                   <%= "Declined"  %>
                <% end %>
              </td>
              <td>
                <%= request.created_at %>
              </td>
            </tr>
        <% end %>
    <% else %>
                <tr>
                  <td colspan ='4' > You didn't send any request yet</td>
                </tr>

    <% end %>
  </table>

app/views/join_team_requests/edit.html.erb
<h1>Editing join_team_request</h1>

<%= form_for(@join_team_request) do |f| %>
  <%= f.error_messages %>

    <%= f.hidden_field :participant_id %>
    <%= f.hidden_field :team_id %>
    <%= f.hidden_field :status %>
  <p>
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </p>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @join_team_request %> |
<%= link_to 'Back', join_team_requests_path %>

app/views/join_team_requests/new.html.erb
<h1>Sending request to join team "<%= Team.find(params[:team_id]).name %>" </h1>
<%= form_tag :action => 'create', :assignment_id=>params[:assignment_id],:team_id=>params[:team_id],:controller => 'join_team_requests' do %>
 <%= form_for(@join_team_request) do |f| %>
    <p>
      <b>Desired Qualification</b>   <br>
      <%= Team.find(params[:team_id]).comments_for_advertisement %>
    </p>
    <p>
      <%= f.label :comments %>
      <img src="/images/info.png" title="Please specify why you are qualified.">  <br>
      <%= text_area 'comments', "" %>
    </p>
    <p>
      <%= f.submit 'Create' %>
    </p>
  <% end %>
<% end %>

app/views/join_team_requests/show.html.erb
 <p>
  <b>Team:</b> <br>
  <%=h Team.find(@join_team_request.team_id).name %>
</p>

<p>
  <b>Comments:</b>  <br>
  <%=h @join_team_request.comments %>
</p>

<p>
  <b>Status:</b>  <br>
  <% if @join_team_request.status=="P" %>
      Pending: A request has been made to join this team.
    <% else if @join_team_request.status=="D"%>
      Denied: The team has denied your request.
      <% else if @join_team_request.status=="A"%>
      Accepted: The team has accepted your request. <br>
      You should receive an invitation in "Your Team".
       <% else %>
       <%=  @join_team_request.status %>
       <% end %>
      <% end %>
  <% end %>

</p>


<%= link_to 'Edit Comment', edit_join_team_request_path(@join_team_request) %>